## [✔] COMPLETO

# Exercício:

In [99]:
import pandas as pd
import numpy as np

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [100]:
p = 2.0 + 3.0 / 5.0 == 10
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
r = 10 <= p / q + 33.8 < 100
s = 5 != p / (q + r)
t = 33 == s * 2

print(p and q and r and s and t)

print("Usando 'or' ao invés de 'and' podemos inverter o resultado:")

print(p or q or r or s or t)

False
Usando 'or' ao invés de 'and' podemos inverter o resultado:
True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [101]:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
s = ['a',1,True,'b',0,False] > ['a',True,1]
t = ['a',1,True,'b',0,False] == 1
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

print(p and q and r and s and t)

print("'Not' nega o booleano, invertendo seu resultado:")
print("Então, apenas colocando o 'not' para negar o resultado final é possível inverte-lo")

print(not(p and q and not r and s and not t))

False
'Not' nega o booleano, invertendo seu resultado:
Então, apenas colocando o 'not' para negar o resultado final é possível inverte-lo
True

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [102]:
df_atividade_sete = pd.read_csv("./data/df_atividade_07.csv", index_col="Unnamed: 0").round(3)

print("A segunda linha é igual a terceira (a) ou a terceira linha é igual a quarta? (b)")

a = (df_atividade_sete.iloc[1] == df_atividade_sete.iloc[2]).all()
b = (df_atividade_sete.iloc[2] == df_atividade_sete.iloc[3]).all()

print(f"a = {a} e b = {b} == {a or b}")

A segunda linha é igual a terceira (a) ou a terceira linha é igual a quarta? (b)
a = False e b = False == False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [103]:
(df_atividade_sete.iloc[0] >= 10).all()

# df.all() (and) df.any() (or)

False

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [104]:
((df_atividade_sete.iloc[:, 2] >= 0) & (df_atividade_sete.iloc[:, 2] < 40)).all()

True

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [105]:
(df_atividade_sete.iloc[-1] > 10).any()

False

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [106]:
df_atividade_sete[(df_atividade_sete > 5) & (df_atividade_sete < 7)]

         0      1   2      3  Médias
0      NaN    NaN NaN    NaN     NaN
1      NaN    NaN NaN  5.893     NaN
2      NaN    NaN NaN    NaN     NaN
3      NaN    NaN NaN    NaN     NaN
4      NaN  5.893 NaN    NaN     NaN
Médias NaN    NaN NaN    NaN   5.015

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [107]:
df_atividade_sete[(df_atividade_sete <= 5) | (df_atividade_sete > 7)]

             0      1       2      3  Médias
0        2.600  2.800  34.729  0.069  10.050
1        0.139  1.612   1.673    NaN   2.329
2        0.263  0.372   2.600  2.800   1.509
3       34.729  0.069   0.139  1.612   9.137
4        1.673    NaN   0.263  0.372   2.050
Médias   7.881  2.149   7.881  2.149     NaN

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [108]:
array_penultima = np.array(df_atividade_sete.iloc[:, -2])
array_ultima = np.array(df_atividade_sete.iloc[:, -1])

(array_penultima >= 2).any() and (array_penultima <= 5).any()

True

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [109]:
a = (array_penultima > -1).all() and (array_penultima < 12).all()
b = (array_ultima > -1).all() and (array_ultima < 12).all()

a and b

True